In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score,confusion_matrix
print("Done")

Done


In [34]:
url = "iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)  

X = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, 4].values  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)
classifier = KNeighborsClassifier(n_neighbors=6)  
classifier.fit(X_train, y_train)  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [35]:
y_pred = classifier.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
print(df[0:16])

             Actual        Predicted
0    Iris-virginica   Iris-virginica
1    Iris-virginica   Iris-virginica
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5   Iris-versicolor  Iris-versicolor
6       Iris-setosa      Iris-setosa
7   Iris-versicolor  Iris-versicolor
8       Iris-setosa      Iris-setosa
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15   Iris-virginica   Iris-virginica


In [36]:
ACC = accuracy_score(y_test, y_pred)
print("The accuracy of model is "+str(ACC*100)+"%")
CONFMATRIX = confusion_matrix(y_test,y_pred)
print("The confusion matrix is as follows:")
print(CONFMATRIX)

The accuracy of model is 100.0%
The confusion matrix is as follows:
[[13  0  0]
 [ 0 11  0]
 [ 0  0  6]]
