In [1]:
import numpy as np
#Printing a simple 3*3 Array
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The array is")
print(a)

The array is
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#Printing the Array dimension
print("The dimensions are")
print(a.ndim)

#Printing itemsize
print("The itemsize is ")
print(a.itemsize)

#Printing the type stored in Numpy Array
print("The data-type stored in array is ")
print(a.dtype)

The dimensions are
2
The itemsize is 
8
The data-type stored in array is 
int64


In [3]:
#Printing the size of Array OR Total number of elements in y
print("Total number of elements in Array:-")
print(a.size)

#Printing the shape of Numpy Array
print("Shape of array is:-")
print(a.shape)

#Re-shaping an Array
b = np.array([(1,2,3,4),(5,6,7,8)])
print("Before reshaping, array was:-")
print(b)
Brshp = b.reshape(4,2)
print("After reshapping, array is ")
print(Brshp)

Total number of elements in Array:-
9
Shape of array is:-
(3, 3)
Before reshaping, array was:-
[[1 2 3 4]
 [5 6 7 8]]
After reshapping, array is 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#Accessing a particular element

print("The element at 2,2 is "+ str(a[2,2]))
print("The element at 1,0 is "+str(a[1,0]))


#Slicing a numpy array

A = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print("The sliced array is:-")
print(A[0:2,2])


#Getting Equally spaced values between two numbers:-

V1to10by5 = np.linspace(1,10,5)
print("1 to 10 equally spaced:-")
print(V1to10by5)

#Getting Max, Min and sum

a = np.array([(1,2,3),(4,5,6),(7,89,0)])
print("Max of array: "+ str(a.max()))
print("Min of array: "+ str(a.min()))
print("Sum of all elements in array: "+ str(a.sum()))

The element at 2,2 is 9
The element at 1,0 is 4
The sliced array is:-
[3 7]
1 to 10 equally spaced:-
[ 1.    3.25  5.5   7.75 10.  ]
Max of array: 89
Min of array: 0
Sum of all elements in array: 117


In [5]:
#Axis Sums (Sums on Rows and sums on Columns)

a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("Column vise sum is "+ str(a.sum(axis=0))) #Column vise sum
print("Row vise sum is "+ str(a.sum(axis=1))) #Row vise sum

#Finding the Square root and Stdev
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The square rooted array is :-")
print(np.sqrt(a)) #getting Square roots
print("Stdev in Array elements is "+ str(np.std(a)))

#Basic Mathematical Operations
A = np.array([(1,2,3),(4,5,6)])
B = np.array([(10,20,30),(40,50,60)])

print("Sum:-")
print(A+B)

print("Difference:- ")
print(A-B)

print("Element vise Product:-")
print(A*B)

print("Element vise Division:-")
print(A/B)

Column vise sum is [12 15 18]
Row vise sum is [ 6 15 24]
The square rooted array is :-
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
Stdev in Array elements is 2.581988897471611
Sum:-
[[11 22 33]
 [44 55 66]]
Difference:- 
[[ -9 -18 -27]
 [-36 -45 -54]]
Element vise Product:-
[[ 10  40  90]
 [160 250 360]]
Element vise Division:-
[[0 0 0]
 [0 0 0]]


In [6]:
#Vertical Stacking

print("AFter vertical stacking:-")
print(np.vstack((A,B)))

#Horizontal Stacking

print("AFter horizontal stacking:-")
print(np.hstack((A,B)))


#Merging all elements row vise into a single dimensional list
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("Merging via Ravel function:-")
print(a.ravel())

AFter vertical stacking:-
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
AFter horizontal stacking:-
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
Merging via Ravel function:-
[1 2 3 4 5 6 7 8 9]


In [8]:
x = np.arange(0,3*np.pi,0.1)
#Broadcasting An array

A = np.array([1,2,3])
B = np.array([4,5,6])
C = A.__mul__(2)
print("The Broadcasted array is ")
print(C)

The Broadcasted array is 
[2 4 6]


In [9]:
#Transposing a numpy Array

A = np.array([(1,1),(2,2),(3,3)])
print("Before Transposing:-")
print(A)
print("After transposing:-")
B = A.transpose()
print(B)

Before Transposing:-
[[1 1]
 [2 2]
 [3 3]]
After transposing:-
[[1 2 3]
 [1 2 3]]


In [10]:
#Multiplying Two matrices
A = np.matrix(((2,3),(4,5)))
B = np.matrix(((1,0),(0,1)))
C = A * B
print("The multiplied matrix is ")
print(C)


The multiplied matrix is 
[[2 3]
 [4 5]]
